version: '2'
services:
    db:
        image: postgres
        volumes:
            - ./db:/var/lib/postgresql/data/pgdata
        ports:
            - 5428:5432
        environment:
            - POSTGRES_USER=bot
            - POSTGRES_DB=msgdatabase
            - POSTGRES_PASSWORD=11111111
            - PGDATA=/var/lib/postgresql/data/pgdata
